### ISSUE TITLE
Compatibility Issue with EvilCraft

### ISSUE THREAD

**Issue by princessbinas** [blay09/TCInventoryScanning#20]
I have been told that this mod, which I have with Thaumic JEI and Thaumic Periphery, is interacting with EvilCraft, causing problems with the Vengeance Focus. I have tested this and I can confirm this mod is interacting with EvilCraft. Here is more details in these issues that I opened while troubleshooting.

Thaumcraft Beta:
https://github.com/Azanor/thaumcraft-beta/issues/1009

EvilCraft/Cyclops MC:
https://github.com/CyclopsMC/EvilCraft/issues/701

**Comment by BlayTheNinth** [comment]
This issue is not happening to me in singleplayer using

- Minecraft Forge 14.23.4.2708
- Cyclops Core 0.11.6
- EvilCraft 0.10.58
- Thaumcraft 6.1.BETA16
- Thaumic Inventory Scanning 2.0.10

However, it is happening when playing on a server, and even when Thaumic Inventory Scanning is not loaded, so it's most likely an issue on EvilCraft's side after all.

I assume the error occured in multiplayer, but you tested without Inventory Scanning in singleplayer, making it look as if the issue was solved by removing the mod.

**Comment by princessbinas** [comment]
I  have tested with and without Inventory Scanning. I have used EvilCraft  before with tons of other mods (the Dark MagicTech modpack to be exact)  with NO ISSUES. Only when I removed Thaumic Inventory Scanning did  Vengeance Focus work again. 

I have the following: 
Forge 12.23.4.2705 
Cyclops Core 0.11.6 
EvilCraft 10.58 
Thaumcraft 6.1.BETA16 
Thaumic Inventory Scanning 2.0.10 
Thaumic JEI 1.4.0-14 

I thought I had Thaumic Periphery in the modpack, but it turns out I  do not. I was must definitely in Single Player. I am not on a  multiplayer server at this time nor was I when the glitch happened.  Please note that I would have specified multiplayer if it were the case. 

And as ruben said, EvilCraft DOES NOT interact with Thaumcraft in  that way. It only provides extra essentia sources like condensed blood  having essentia. Even Anazor confirmed this. It's your mod causing this issue.
